server:
  port: 8080
spring:
  application:
    name: reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cache:
    redis:
      time-to-live: 18000000
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtps
    username: 1943948147@qq.com
    password: evailudfsrxyjefi
#
    properties:
      smtp:
        ssl:
          enable: true
          trust: smtp.qq.com
        auth: true
        auth.mechanisms: true
        starttls:
          enable: true
          required: true
    default-encoding: utf-8
zijun:
  mail:
    sender: 1943948147@qq.com
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: E:\Workspace IDEA\reggie\src\main\resources\static\uploads\